// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwjgehcjapvsljmdblks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3amdlaGNqYXB2c2xqbWRibGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjI0ODQsImV4cCI6MjA1ODUzODQ4NH0.83lQZvKp18BagoQ0XfACC6RUol8XqE5hdkNknpi8gTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);